apiVersion: v1
kind: Service
metadata:
  name: node-port
  namespace: ns-2
spec:
  type: NodePort  
  selector:
    app: nginx
  ports:
  - name: port-np
    port: 8080  #service port
    targetPort: 80  #container port

